### ISSUE TITLE
能截图看看不，我有时候也不方便上班时间查看，

### ISSUE THREAD

**Issue by alvin198761** [yangshangshe/SwingQQ2011#1]
你的好几个项目好像都没有图，能截图看看不

**Comment by yangshangshe** [comment]
不好意思，都是很久以前弄的，代码都扔了，不好截图了。



 
发件人： 月球王子
发送时间： 2017-02-13 14:46
收件人： yangshangshe/SwingQQ2011
抄送： Subscribed
主题： [yangshangshe/SwingQQ2011] 能截图看看不，我有时候也不方便上班时间查看， (#1)
你的好几个项目好像都没有图，能截图看看不
